### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by TekMath** [Ilade-s/Synthetiseur-Tk#1]
# Synthetiseur-Tk

## Install libs
`pip install -r requirements.txt`

## Class
`class Clavier(Frame):` _Keys of the instrument_
`class Synth(Tk):` _Global window/GUI_

## Infomations
AUTHOR : `Merlet Raphaël` | `VERSION : 1.0`

**Comment by Ilade-s** [comment]
J'ai copié ta proposition et l'ai mise en tant que readme
